-- Summit Scrap Prototype v0.1
-- Supabase Dashboard > SQL Editor에서 전체를 한 번 실행하세요.

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 2 and 20),
  created_at timestamptz not null default now()
);

create table public.game_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stage integer not null check (stage > 0),
  clear_time_ms integer not null check (clear_time_ms > 0),
  created_at timestamptz not null default now()
);

create index game_records_stage_time_idx on public.game_records(stage, clear_time_ms);
create index game_records_user_stage_idx on public.game_records(user_id, stage);

alter table public.profiles enable row level security;
alter table public.game_records enable row level security;

create policy "profiles are publicly readable for rankings"
on public.profiles for select using (true);
create policy "users can update their own profile"
on public.profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users can read their own raw records"
on public.game_records for select using (auth.uid() = user_id);
create policy "users can insert their own records"
on public.game_records for insert with check (auth.uid() = user_id);
create policy "users can delete their own records"
on public.game_records for delete using (auth.uid() = user_id);

-- Auth 회원이 생성되면 metadata의 nickname으로 프로필을 자동 생성합니다.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (user_id, nickname)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'nickname', ''), 'Climber'));
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 원본 기록은 비공개로 유지하면서, 사용자별 Stage 1 최고 기록만 공개합니다.
create or replace view public.stage1_leaderboard
with (security_invoker = false)
as
select r.user_id, p.nickname, min(r.clear_time_ms)::integer as clear_time_ms
from public.game_records r
join public.profiles p on p.user_id = r.user_id
where r.stage = 1
group by r.user_id, p.nickname
order by clear_time_ms asc;

grant select on public.stage1_leaderboard to authenticated;
revoke all on public.stage1_leaderboard from anon;

